import { describe, test, expect } from 'vitest';
import shippedKnowledgeBase from '../../data/knowledge-base.json';

/**
 * Dead internal links in a knowledge base, as `from -> to` strings.
 *
 * `fetch-docs.js` rewrites relative .md links into Knowledge Center routes
 * whether or not the target was published, so a link to a doc missing from the
 * mkdocs nav becomes a plausible URL that renders "not found". Two shipped that
 * way, both to analysis-human-precovid-sed-adu-c2.0.
 */
function deadLinks(knowledgeBase) {
  const { categories = [], documents = [] } = knowledgeBase;

  const routes = new Set(['/knowledge-center']);
  categories.forEach((category) => {
    routes.add(`/knowledge-center/${category.slug}`);
    (category.subcategories || []).forEach((sub) => {
      routes.add(`/knowledge-center/${category.slug}/${sub.slug}`);
    });
  });
  documents.forEach((doc) => {
    const parts = [doc.category, doc.subcategory, doc.slug].filter(Boolean);
    routes.add(`/knowledge-center/${parts.join('/')}`);
  });

  const dead = [];
  documents.forEach((doc) => {
    const matches = (doc.content || '').matchAll(/\]\((\/knowledge-center[^)\s]*)\)/g);
    for (const match of matches) {
      const to = match[1].split('#')[0].split('?')[0].replace(/\/$/, '');
      if (!routes.has(to)) {
        dead.push(`${doc.category}/${doc.subcategory || ''}/${doc.slug} -> ${to}`);
      }
    }
  });
  return dead;
}

/** Published routes carrying a segment that was interpolated from null. */
function nullSegmentRoutes(knowledgeBase) {
  const { categories = [], documents = [] } = knowledgeBase;
  const routes = [
    ...categories.flatMap((category) => [
      `/knowledge-center/${category.slug}`,
      ...(category.subcategories || []).map(
        (sub) => `/knowledge-center/${category.slug}/${sub.slug}`
      ),
    ]),
    ...documents.map(
      (doc) =>
        `/knowledge-center/${[doc.category, doc.subcategory, doc.slug].filter(Boolean).join('/')}`
    ),
  ];
  return routes.filter((route) => /\/(null|undefined)(\/|$)/.test(route));
}

// The knowledge base committed to the repo is an empty scaffold; the real one is
// generated by `yarn fetch-docs` from a private repo and is not committed. So
// the checks below must earn their keep against a fixture -- run only against
// the shipped file they would pass on emptiness and prove nothing.
const FIXTURE = {
  categories: [
    { slug: 'data-collections', subcategories: [{ slug: 'analysis-results' }] },
  ],
  documents: [
    {
      category: 'data-collections',
      subcategory: 'analysis-results',
      slug: 'published',
      content: 'see [the other one](/knowledge-center/data-collections/analysis-results/published)',
    },
  ],
};

describe('the dead-link check itself', () => {
  test('accepts a link to a document that was published', () => {
    expect(deadLinks(FIXTURE)).toEqual([]);
  });

  test('flags a link to one that was not', () => {
    // The exact shape of the bug: a route built from the folder name
    // (`analysis-collections`) where the nav publishes under the label slug
    // (`analysis-results`).
    const withDeadLink = {
      ...FIXTURE,
      documents: [
        {
          ...FIXTURE.documents[0],
          content: 'see [the other one](/knowledge-center/data-collections/analysis-collections/missing)',
        },
      ],
    };

    expect(deadLinks(withDeadLink)).toEqual([
      'data-collections/analysis-results/published -> /knowledge-center/data-collections/analysis-collections/missing',
    ]);
  });

  test('ignores the anchor and query when resolving', () => {
    const withAnchor = {
      ...FIXTURE,
      documents: [
        {
          ...FIXTURE.documents[0],
          content: '[x](/knowledge-center/data-collections/analysis-results/published#section)',
        },
      ],
    };

    expect(deadLinks(withAnchor)).toEqual([]);
  });

  test('flags a route interpolated from a null category', () => {
    // Routes are assembled by concatenation, so a missing category once
    // produced "/knowledge-center/null/<slug>" instead of the root-level route.
    expect(nullSegmentRoutes(FIXTURE)).toEqual([]);
    expect(
      nullSegmentRoutes({
        categories: [],
        documents: [{ category: null, subcategory: null, slug: 'glossary' }],
      })
    ).toEqual([]);
    expect(
      nullSegmentRoutes({
        categories: [],
        documents: [{ category: 'null', subcategory: null, slug: 'glossary' }],
      })
    ).toEqual(['/knowledge-center/null/glossary']);
  });
});

describe('the shipped knowledge base', () => {
  // Vacuous against the committed scaffold, which is why the checks above exist.
  // Meaningful wherever the real corpus is present: a local run after
  // `yarn fetch-docs`, and any build that generates it before testing.
  test('has no dead internal links', () => {
    expect(deadLinks(shippedKnowledgeBase)).toEqual([]);
  });

  test('has no route with a null segment', () => {
    expect(nullSegmentRoutes(shippedKnowledgeBase)).toEqual([]);
  });

  test('files every unlisted doc under a category that exists', () => {
    // Unlisted docs inherit their placement from a listed sibling rather than
    // from their folder, so their category and subcategory must both resolve.
    const { categories = [], documents = [] } = shippedKnowledgeBase;

    documents
      .filter((doc) => doc.unlisted)
      .forEach((doc) => {
        const category = categories.find((c) => c.slug === doc.category);
        expect(category, `${doc.slug} has no category`).toBeDefined();
        if (doc.subcategory) {
          const sub = (category.subcategories || []).find((s) => s.slug === doc.subcategory);
          expect(sub, `${doc.slug} has no subcategory`).toBeDefined();
        }
      });
  });
});
