const assays = [
  {
    omics_code: 'transcriptomics',
    submission_code: null,
    assay_code: 'transcript-rna-seq',
    assay_name: 'RNA-seq',
    cas_code: ['stanford', 'mssm'],
  },
  {
    omics_code: 'epigenomics',
    submission_code: null,
    assay_code: 'epigen-rrbs',
    assay_name: 'RRBS',
    cas_code: ['mssm'],
  },
  {
    omics_code: 'epigenomics',
    submission_code: null,
    assay_code: 'epigen-atac-seq',
    assay_name: 'ATAC-seq',
    cas_code: ['stanford'],
  },
  {
    omics_code: 'metabolomics-targeted',
    submission_code: '3HIB',
    assay_code: 'metab-t-3hib',
    assay_name: 'Targeted 3-Hydroxyisobutyric Acid (3-HIB)',
    cas_code: ['duke'],
  },
  {
    omics_code: 'metabolomics-targeted',
    submission_code: 'AA',
    assay_code: 'metab-t-aa',
    assay_name: 'Targeted Amino Acids',
    cas_code: ['duke'],
  },
  {
    omics_code: 'metabolomics-targeted',
    submission_code: 'AC_DUKE',
    assay_code: 'metab-t-ac-duke',
    assay_name: 'Targeted Acylcarnitines',
    cas_code: ['duke'],
  },
  {
    omics_code: 'metabolomics-targeted',
    submission_code: 'ACOA',
    assay_code: 'metab-t-acoa',
    assay_name: 'Targeted Acyl-CoA',
    cas_code: ['duke'],
  },
  {
    omics_code: 'metabolomics-targeted',
    submission_code: 'BAIBA',
    assay_code: 'metab-t-baiba',
    assay_name: 'Targeted Beta-aminoisobutyric acid (BAIBA)',
    cas_code: ['duke'],
  },
  {
    omics_code: 'metabolomics-targeted',
    submission_code: 'CER_DUKE',
    assay_code: 'metab-t-cer-duke',
    assay_name: 'Targeted Ceramide',
    cas_code: ['duke'],
  },
  {
    omics_code: 'metabolomics-targeted',
    submission_code: 'CON',
    assay_code: 'metab-t-con',
    assay_name: 'Targeted Conventional',
    cas_code: ['duke'],
  },
  {
    omics_code: 'metabolomics-targeted',
    submission_code: 'KA',
    assay_code: 'metab-t-ka',
    assay_name: 'Targeted Keto acids (KA)',
    cas_code: ['duke'],
  },
  {
    omics_code: 'metabolomics-targeted',
    submission_code: 'NUC',
    assay_code: 'metab-t-nuc',
    assay_name: 'Targeted Nucleotides',
    cas_code: ['duke'],
  },
  {
    omics_code: 'metabolomics-targeted',
    submission_code: 'OA',
    assay_code: 'metab-t-oa',
    assay_name: 'Targeted Organic acids (OA)',
    cas_code: ['duke'],
  },
  {
    omics_code: 'metabolomics-targeted',
    submission_code: 'SPHM',
    assay_code: 'metab-t-sphm',
    assay_name: 'Targeted Sphingomyelin',
    cas_code: ['duke'],
  },
  {
    omics_code: 'metabolomics-targeted',
    submission_code: 'OXYLIPNEG',
    assay_code: 'metab-t-oxylipneg',
    assay_name: 'Targeted Oxylipins (Emory)',
    cas_code: ['emory'],
  },
  {
    omics_code: 'metabolomics-targeted',
    submission_code: 'AC_MAYO',
    assay_code: 'metab-t-ac-mayo',
    assay_name: 'Targeted Acylcarnitines (Mayo)',
    cas_code: ['mayo'],
  },
  {
    omics_code: 'metabolomics-targeted',
    submission_code: 'AMINES',
    assay_code: 'metab-t-amines',
    assay_name: 'Targeted Amines (Mayo)',
    cas_code: ['mayo'],
  },
  {
    omics_code: 'metabolomics-targeted',
    submission_code: 'CER_MAYO',
    assay_code: 'metab-t-cer-mayo',
    assay_name: 'Targeted Ceramides (Mayo)',
    cas_code: ['mayo'],
  },
  {
    omics_code: 'metabolomics-targeted',
    submission_code: 'TCA',
    assay_code: 'metab-t-tca',
    assay_name: 'Targeted Tricarboxylic acid (TCA) cycle ',
    cas_code: ['mayo'],
  },
  {
    omics_code: 'metabolomics-untargeted',
    submission_code: 'HILICPOS',
    assay_code: 'metab-u-hilicpos',
    assay_name: 'Untargeted HILIC-positive (Broad)',
    cas_code: ['broad_met'],
  },
  {
    omics_code: 'metabolomics-untargeted',
    submission_code: 'LRPNEG',
    assay_code: 'metab-u-lrpneg',
    assay_name: 'Untargeted Lipidomics, reversed-phase negative',
    cas_code: ['gtech'],
  },
  {
    omics_code: 'metabolomics-untargeted',
    submission_code: 'LRPPOS',
    assay_code: 'metab-u-lrppos',
    assay_name: 'Untargeted Lipidomics, reversed-phase positive',
    cas_code: ['gtech'],
  },
  {
    omics_code: 'metabolomics-untargeted',
    submission_code: 'RPPOS',
    assay_code: 'metab-u-rppos',
    assay_name: 'Untargeted Reversed-phase positive',
    cas_code: ['umichigan'],
  },
  {
    omics_code: 'metabolomics-untargeted',
    submission_code: 'RPNEG',
    assay_code: 'metab-u-rpneg',
    assay_name: 'Untargeted Reversed-phase negative',
    cas_code: ['umichigan'],
  },
  {
    omics_code: 'metabolomics-untargeted',
    submission_code: 'IONPNEG',
    assay_code: 'metab-u-ionpneg',
    assay_name: 'Untargeted Ion-Pair negative',
    cas_code: ['umichigan'],
  },
  {
    omics_code: 'proteomics',
    submission_code: 'PROT_PR',
    assay_code: 'prot-pr',
    assay_name: 'Global Proteomics',
    cas_code: ['broad_prot', 'pnnl'],
  },
  {
    omics_code: 'proteomics',
    submission_code: 'PROT_PH',
    assay_code: 'prot-ph',
    assay_name: 'Phophoproteomics',
    cas_code: ['broad_prot', 'pnnl'],
  },
  {
    omics_code: 'proteomics',
    submission_code: 'PROT_AC',
    assay_code: 'prot-ac',
    assay_name: 'Acetyl Proteomics',
    cas_code: ['broad_prot'],
  },
];

export default assays;
