language: en-US
tone_instructions: 'You are an expert code reviewer in React, TypeScript, JavaScript, and NodeJS. You work in an agile software developer team, providing concise and clear code review advice. You only elaborate or provide detailed explanations when requested.'
early_access: false
enable_free_tier: true
reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: '@coderabbitai summary'
  high_level_summary_in_walkthrough: false
  auto_title_placeholder: '@coderabbitai'
  auto_title_instructions: ''
  review_status: true
  commit_status: true
  fail_commit_status: false
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: true
  estimate_code_review_effort: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  labeling_instructions: []
  auto_apply_labels: false
  suggested_reviewers: true
  auto_assign_reviewers: false
  in_progress_fortune: true
  poem: true
  path_filters:
    - '!**/*.xml'
    - '!**/*.json'
    - '!**/*.md'
    - '!**/*.yml'
    - '!**/*.yaml'
    - '!**/*.txt'
    - '!**/*.html'
    - '!**/*.svg'
  path_instructions:
    - path: '**/*.{css,scss,sass,less}'
      instructions: |
        'Review the CSS code against the google css style guide and point out any mismatches. Ensure that:
        - The code adheres to best practices associated with CSS.
        - The code adheres to best practices recommended by lighthouse or similar tools for performance.
        - The code adheres to similar naming conventions for classes, ids.'
    - path: '**/*.{js,jsx,ts,tsx}'
      instructions: |
        'Focus on code quality, performance, and security best practices for JavaScript and TypeScript files. Ensure that:
        - Code adheres to modern JavaScript/TypeScript standards and ES6+ features.
        - The code adheres to best practices associated with React.
        - The code adheres to best practices associated with React PWA.
        - The code adheres to best practices associated with SPA.
        - Proper error handling is implemented.
        - Security vulnerabilities such as XSS, CSRF, and injection attacks are mitigated.
        - Performance optimizations are considered, especially for large data sets or complex computations.
        - Code is modular, reusable, and follows SOLID principles where applicable.
        - Type safety is enforced in TypeScript files, with appropriate use of interfaces and types.'
  abort_on_close: true
  disable_cache: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords:
      - 'WIP'
      - 'DO NOT MERGE'
      - 'DRAFT'
    labels: []
    drafts: false
    base_branches:
      - 'main'
      - 'master'
      - 'develop'
      - 'dev'
      - 'release/.*'
    ignore_usernames: []
  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true
  pre_merge_checks:
    docstrings:
      mode: warning
      threshold: 80
    title:
      mode: warning
      requirements: ''
    description:
      mode: warning
    issue_assessment:
      mode: warning
    custom_checks: []
  tools:
    ast-grep:
      rule_dirs: []
      util_dirs: []
      essential_rules: true
      packages: []
    shellcheck:
      enabled: true
    ruff:
      enabled: true
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: true
      enabled_rules: []
      disabled_rules: []
      enabled_categories: []
      disabled_categories: []
      enabled_only: false
      level: default
    biome:
      enabled: true
    hadolint:
      enabled: true
    swiftlint:
      enabled: true
    phpstan:
      enabled: true
      level: default
    phpmd:
      enabled: true
    phpcs:
      enabled: true
    golangci-lint:
      enabled: true
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    checkov:
      enabled: true
    detekt:
      enabled: true
    eslint:
      enabled: true
    flake8:
      enabled: true
    rubocop:
      enabled: true
    buf:
      enabled: true
    regal:
      enabled: true
    actionlint:
      enabled: true
    pmd:
      enabled: true
    clang:
      enabled: true
    cppcheck:
      enabled: true
    semgrep:
      enabled: true
    circleci:
      enabled: true
    clippy:
      enabled: true
    sqlfluff:
      enabled: true
    prismaLint:
      enabled: true
    pylint:
      enabled: true
    oxc:
      enabled: true
    shopifyThemeCheck:
      enabled: true
    luacheck:
      enabled: true
    brakeman:
      enabled: true
    dotenvLint:
      enabled: true
    htmlhint:
      enabled: true
    checkmake:
      enabled: true
    osvScanner:
      enabled: true
chat:
  art: true
  auto_reply: true
  integrations:
    jira:
      usage: auto
    linear:
      usage: auto
knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns: []
  learnings:
    scope: auto
  issues:
    scope: auto
  jira:
    usage: auto
    project_keys: []
  linear:
    usage: auto
    team_keys: []
  pull_requests:
    scope: auto
  mcp:
    usage: auto
    disabled_servers: []
code_generation:
  docstrings:
    language: en-US
    path_instructions: []
  unit_tests:
    path_instructions: []
