# create-react-app build environment
FROM node:20-alpine as react-build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
RUN corepack enable

ARG VITE_ES_PROXY_HOST
ARG VITE_API_SERVICE_ADDRESS
ARG VITE_API_SERVICE_KEY
ARG VITE_SIGNED_URL_ENDPOINT
ARG VITE_USER_REGISTRATION_ENDPOINT
ARG VITE_SEND_EMAIL_ENDPOINT
ARG VITE_FILE_DOWNLOAD_ENDPOINT
ARG VITE_QC_DATA_ENDPOINT
ARG VITE_ES_ENDPOINT
ARG VITE_FILE_SEARCH_ENDPOINT
ARG VITE_DATA_FILE_BUCKET
ARG VITE_QC_REPORT_BUCKET
ARG VITE_ES_ACCESS_TOKEN
ARG VITE_reCAPTCHA_SITE_KEY
ARG VITE_AUTH0_CLIENT_ID
ARG VITE_QUALTRICS_SURVEY_URL
ARG VITE_USER_SURVEY_SUBMIT_URL
ARG VITE_USER_SURVEY_INPUT_1
ARG VITE_USER_SURVEY_INPUT_2
ARG VITE_USER_SURVEY_INPUT_3
ARG VITE_USER_SURVEY_INPUT_4
ARG VITE_USER_SURVEY_INPUT_5
ARG VITE_OFFICE_HOUR_DAY
ARG VITE_OFFICE_HOUR_DATE
ARG VITE_OFFICE_HOUR_SIGNUP_URL

ENV ESLINT_NO_DEV_ERRORS true
ENV DISABLE_ESLINT_PLUGIN true
ENV VITE_ES_PROXY_HOST $VITE_ES_PROXY_HOST
ENV VITE_API_SERVICE_ADDRESS $VITE_API_SERVICE_ADDRESS
ENV VITE_API_SERVICE_KEY $VITE_API_SERVICE_KEY
ENV VITE_SIGNED_URL_ENDPOINT $VITE_SIGNED_URL_ENDPOINT
ENV VITE_USER_REGISTRATION_ENDPOINT $VITE_USER_REGISTRATION_ENDPOINT
ENV VITE_SEND_EMAIL_ENDPOINT $VITE_SEND_EMAIL_ENDPOINT
ENV VITE_FILE_DOWNLOAD_ENDPOINT $VITE_FILE_DOWNLOAD_ENDPOINT
ENV VITE_QC_DATA_ENDPOINT $VITE_QC_DATA_ENDPOINT
ENV VITE_ES_ENDPOINT $VITE_ES_ENDPOINT
ENV VITE_FILE_SEARCH_ENDPOINT $VITE_FILE_SEARCH_ENDPOINT
ENV VITE_DATA_FILE_BUCKET $VITE_DATA_FILE_BUCKET
ENV VITE_QC_REPORT_BUCKET $VITE_QC_REPORT_BUCKET
ENV VITE_ES_ACCESS_TOKEN $VITE_ES_ACCESS_TOKEN
ENV VITE_reCAPTCHA_SITE_KEY $VITE_reCAPTCHA_SITE_KEY
ENV VITE_AUTH0_CLIENT_ID $VITE_AUTH0_CLIENT_ID
ENV VITE_QUALTRICS_SURVEY_URL $VITE_QUALTRICS_SURVEY_URL
ENV VITE_USER_SURVEY_SUBMIT_URL $VITE_USER_SURVEY_SUBMIT_URL
ENV VITE_USER_SURVEY_INPUT_1 $VITE_USER_SURVEY_INPUT_1
ENV VITE_USER_SURVEY_INPUT_2 $VITE_USER_SURVEY_INPUT_2
ENV VITE_USER_SURVEY_INPUT_3 $VITE_USER_SURVEY_INPUT_3
ENV VITE_USER_SURVEY_INPUT_4 $VITE_USER_SURVEY_INPUT_4
ENV VITE_USER_SURVEY_INPUT_5 $VITE_USER_SURVEY_INPUT_5
ENV VITE_OFFICE_HOUR_DAY $VITE_OFFICE_HOUR_DAY
ENV VITE_OFFICE_HOUR_DATE $VITE_OFFICE_HOUR_DATE
ENV VITE_OFFICE_HOUR_SIGNUP_URL $VITE_OFFICE_HOUR_SIGNUP_URL


COPY package.json yarn.lock ./
RUN --mount=type=cache,target=/root/.yarn \
  YARN_CACHE_FOLDER=/root/.yarn JOBS=max \
  yarn install --network-timeout 1000000

COPY vite.config.js index.html ./
COPY src ./src
COPY public ./public

RUN --mount=type=cache,target=/root/.yarn \
  YARN_CACHE_FOLDER=/root/.yarn JOBS=max \
  yarn build

# nginx server environment
FROM nginxinc/nginx-unprivileged:1.25-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=react-build /app/build /usr/share/nginx/html

LABEL org.opencontainers.image.description="MoTrPAC Data Portal Docker Image"
LABEL org.opencontainers.image.documentation="https://github.com/MoTrPAC/motrpac-frontend"
LABEL org.opencontainers.image.title="MoTrPAC Data Portal Web Client Server"
LABEL org.opencontainers.image.url="https://motrpac-data.org"
LABEL org.opencontainers.image.vendor="MoTrPAC"
LABEL org.opencontainers.image.version=$IMAGE_VERSION

EXPOSE 8080

