steps:
#Build the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/motrpac-frontend-dev:$SHORT_SHA', '.']
  env:
  - 'DISABLE_ESLINT_PLUGIN=true'

#Push the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/motrpac-frontend-dev:$SHORT_SHA']

# deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernetes/dev/
  - --image=gcr.io/$PROJECT_ID/motrpac-frontend-dev:$SHORT_SHA
  - --location=us-west1-a
  - --cluster=motrpac-frontend-dev-cluster
