steps:
#Build the image
- name: 'gcr.io/cloud-builders/docker'
  env:
  - 'DISABLE_ESLINT_PLUGIN=true'
  - 'REACT_APP_ES_PROXY_HOST=$_REACT_APP_ES_PROXY_HOST'
  - 'REACT_APP_ES_PROXY_HOST_DEV=$_REACT_APP_ES_PROXY_HOST_DEV'
  - 'REACT_APP_API_SERVICE_ADDRESS=$_REACT_APP_API_SERVICE_ADDRESS'
  - 'REACT_APP_API_SERVICE_ADDRESS_DEV=$_REACT_APP_API_SERVICE_ADDRESS_DEV'
  - 'REACT_APP_API_SERVICE_KEY=$_REACT_APP_API_SERVICE_KEY'
  - 'REACT_APP_API_SERVICE_KEY_DEV=$_REACT_APP_API_SERVICE_KEY_DEV'
  - 'REACT_APP_SIGNED_URL_ENDPOINT=$_REACT_APP_SIGNED_URL_ENDPOINT'
  - 'REACT_APP_USER_REGISTRATION_ENDPOINT=$_REACT_APP_USER_REGISTRATION_ENDPOINT'
  - 'REACT_APP_SEND_EMAIL_ENDPOINT=$_REACT_APP_SEND_EMAIL_ENDPOINT'
  - 'REACT_APP_FILE_DOWNLOAD_ENDPOINT=$_REACT_APP_FILE_DOWNLOAD_ENDPOINT'
  - 'REACT_APP_QC_DATA_ENDPOINT=$_REACT_APP_QC_DATA_ENDPOINT'
  - 'REACT_APP_ES_ENDPOINT=$_REACT_APP_ES_ENDPOINT'
  - 'REACT_APP_FILE_SEARCH_ENDPOINT=$_REACT_APP_FILE_SEARCH_ENDPOINT'
  - 'REACT_APP_DATA_FILE_BUCKET=$_REACT_APP_DATA_FILE_BUCKET'
  - 'REACT_APP_QC_REPORT_BUCKET=$_REACT_APP_QC_REPORT_BUCKET'
  - 'REACT_APP_QC_REPORT_BUCKET_DEV=$_REACT_APP_QC_REPORT_BUCKET_DEV'
  - 'REACT_APP_ES_ACCESS_TOKEN=$_REACT_APP_ES_ACCESS_TOKEN'
  - 'REACT_APP_ES_ACCESS_TOKEN_DEV=$_REACT_APP_ES_ACCESS_TOKEN_DEV'
  - 'REACT_APP_reCAPTCHA_SITE_KEY=$_REACT_APP_RECAPTCHA_SITE_KEY'
  - 'REACT_APP_AUTH0_CLIENT_ID=$_REACT_APP_AUTH0_CLIENT_ID'
  script: 'echo $DISABLE_ESLINT_PLUGIN && echo $REACT_APP_ES_PROXY_HOST && echo $REACT_APP_ES_PROXY_HOST_DEV && echo $REACT_APP_API_SERVICE_ADDRESS && echo $REACT_APP_API_SERVICE_ADDRESS_DEV && echo $REACT_APP_API_SERVICE_KEY && echo $REACT_APP_API_SERVICE_KEY_DEV && echo $REACT_APP_SIGNED_URL_ENDPOINT && echo $REACT_APP_USER_REGISTRATION_ENDPOINT && echo $REACT_APP_SEND_EMAIL_ENDPOINT && echo $REACT_APP_FILE_DOWNLOAD_ENDPOINT && echo $REACT_APP_QC_DATA_ENDPOINT && echo $REACT_APP_ES_ENDPOINT && echo $REACT_APP_FILE_SEARCH_ENDPOINT && echo $REACT_APP_DATA_FILE_BUCKET && echo $REACT_APP_QC_REPORT_BUCKET && echo $REACT_APP_QC_REPORT_BUCKET_DEV && echo $REACT_APP_ES_ACCESS_TOKEN && echo $REACT_APP_ES_ACCESS_TOKEN_DEV && echo $REACT_APP_reCAPTCHA_SITE_KEY && echo $REACT_APP_AUTH0_CLIENT_ID'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/motrpac-frontend-dev:$SHORT_SHA', '.']

#Push the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/motrpac-frontend-dev:$SHORT_SHA']

# deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernetes/dev/
  - --image=gcr.io/$PROJECT_ID/motrpac-frontend-dev:$SHORT_SHA
  - --location=us-west1-a
  - --cluster=motrpac-frontend-dev-cluster
